StampBidding/Models/Bidding.cs
using System;
using System.Collections.Generic;

namespace StampBidding.Models
{
    public partial class Bidding
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public DateTime Date { get; set; }
        public string Price { get; set; } = null!;
        public string UserId { get; set; } = null!;

        public virtual Item Item { get; set; } = null!;
        public virtual User User { get; set; } = null!;
    }
}

StampBidding/Controllers/BiddingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Web;
using StampBidding.Models;
using iTextSharp.text.pdf;
using iTextSharp.text.pdf.parser;
using System.Text;

namespace StampBidding.Controllers
{
    public class BiddingController : Controller
    {
        private readonly BidingSystemContext _context;

        public BiddingController(BidingSystemContext context)
        {
            _context = context;
        }

        // GET: Bidding
        public async Task<IActionResult> Index()
        {
            var bidingSystemContext = _context.Biddings.Include(b => b.Item).Include(b => b.User);
            return View(await bidingSystemContext.ToListAsync());
        }

        // GET: Bidding/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Biddings == null)
            {
                return NotFound();
            }

            var bidding = await _context.Biddings
                .Include(b => b.Item)
                .Include(b => b.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bidding == null)
            {
                return NotFound();
            }

            return View(bidding);
        }

        // GET: Bidding/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bidding/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file)
        {
            if (file.Length > 0)
            {
                List<string> outputtext = new List<string>();
                var filePath = System.IO.Path.Combine(Directory.GetCurrentDirectory(), file.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                using(PdfReader reader = new PdfReader(filePath))
                {
                    for (int page = 1;  page <= reader.NumberOfPages; page++)
                    {
                        ITextExtractionStrategy strategy = new SimpleTextExtractionStrategy();
                        string text = PdfTextExtractor.GetTextFromPage(reader, page, strategy);
                        text = Encoding.UTF8.GetString(ASCIIEncoding.Convert(Encoding.Default, Encoding.UTF8, Encoding.Default.GetBytes(text)));
                        outputtext.Add(text.ToString());
                    }
                }
                System.IO.File.Delete(filePath);
                List<int> bids = new List<int>();
                List<int> lots = new List<int>();
                string finalmemberid = "";
                bool loop = false;
                foreach(var text in outputtext)
                {
                    if (loop)
                    {
                        List<string> numbers = new List<string>();
                        bool fault = true;
                        try
                        {
                            var splitted = text.Split("\nADDITIONAL AND ALTERNATIVE BIDS \nAddit").ToList();
                            splitted.Remove(splitted[1]);
                            numbers = splitted[0].Split(" ").ToList();
                            fault = false;
                        }
                        catch (Exception)
                        {

                        }
                        if (fault)
                        {
                            numbers = text.Split(" ").ToList();
                        }
                        List<string> FullySortedNumbers = new List<string>();
                        numbers.RemoveAll(i => i == "");
                        foreach (var number in numbers)
                        {
                            if (number.Contains("\n"))
                            {
                                var tempsplit = number.Split("\n").ToList();
                                tempsplit.RemoveAll(i => i == "");
                                try
                                {
                                    FullySortedNumbers.Add(tempsplit[0]);
                                }
                                catch (Exception)
                                {

                                }
                            }
                            else
                            {
                                FullySortedNumbers.Add(number);
                            }
                        }
                        for (int i = 0; i < FullySortedNumbers.Count();)
                        {
                            if (i % 3 == 0)
                            {
                                lots.Add(Int32.Parse(FullySortedNumbers[i]));
                                i++;
                            }
                            string price = FullySortedNumbers[i] + FullySortedNumbers[i + 1];
                            bids.Add(Int32.Parse(price));
                            i = i + 2;
                        }

                    }
                    else if(text.Contains("\nBLANK \nLOT \nNo \n \nBID LEAVE \nBLANK \n£"))
                    {
                        List<string> splitted = text.Split("£ p £ p £ \n \np \n").ToList();
                        splitted.Remove(splitted[0]);
                        List<string> splittedsecond = splitted[0].Split("       \nName \nAddress \nPostcode \nTelephone \nE-mail \nFor Auctioneer’s use  \nMembership Number \nI have read and agree to abide by the rules of the  \nModern British Philatelic Circle which govern  \nSignature  .............").ToList();
                        string memberid = splittedsecond[1].Substring(splittedsecond[1].Length - 9);
                        List<string> evalmemberId = new List<string>();
                        List<string> splitmemberid = memberid.Split(" ").ToList();
                        foreach(var member in splitmemberid)
                        {
                            if (member.Contains("\n"))
                            {
                                var tempsplit = member.Split("\n").ToList();
                                tempsplit.RemoveAll(i => i == "");
                                evalmemberId.Add(tempsplit[0]);
                            }
                            else
                            {
                                evalmemberId.Add(member);
                            }
                        }
                        try
                        {
                            evalmemberId.RemoveAll(i => i == "");
                        }
                        catch (Exception)
                        {

                        }
                        foreach (var eval in evalmemberId)
                        {
                            finalmemberid = finalmemberid+eval;
                        }
                        splittedsecond.Remove(splittedsecond[1]);
                        List<string> numbers = splittedsecond[0].Split(" ").ToList();
                        List<string> FullySortedNumbers = new List<string>();
                        numbers.RemoveAll(i => i == "");
                        foreach(var number in numbers)
                        {
                            if (number.Contains("\n"))
                            {
                                var tempsplit = number.Split("\n").ToList();
                                tempsplit.RemoveAll(i => i == "");
                                try
                                {
                                    FullySortedNumbers.Add(tempsplit[0]);
                                }
                                catch (Exception)
                                {

                                }
                            }
                            else
                            {
                                FullySortedNumbers.Add(number);
                            }
                        }
                        for (int i = 0; i < FullySortedNumbers.Count();)
                        {
                            if (i % 3 == 0)
                            {
                                lots.Add(Int32.Parse(FullySortedNumbers[i]));
                                i++;
                            }
                            string price = FullySortedNumbers[i] + FullySortedNumbers[i + 1];
                            bids.Add(Int32.Parse(price));
                            i = i + 2;
                        }
                        loop = true;
                    }
                }
                var currentuser = _context.Users.First(i => i.MemberId == Int32.Parse(finalmemberid));
                for (int i = 0; i < lots.Count; i++)
                {
                    Bidding bidding = new Bidding
                    {
                        ItemId = lots[i],
                        Date = DateTime.Now,
                        Price = bids[i].ToString(),
                        UserId = currentuser.Uuid
                    };
                    _context.Add(bidding);
                    await _context.SaveChangesAsync();
                }
            }
            return View();
        }

        // GET: Bidding/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Biddings == null)
            {
                return NotFound();
            }

            var bidding = await _context.Biddings.FindAsync(id);
            if (bidding == null)
            {
                return NotFound();
            }

StampBidding/Views/Bidding/Create.cshtml
@model StampBidding.Models.Bidding

@{
    ViewData["Title"] = "Create";
}
<form method="post" enctype="multipart/form-data" asp-controller="Bidding" asp-action="Create">
    <div class="text-center">
        <h3 class="blockquote">To place a bidding, you must file out the provided PDF</h3>
        <input type="file" class="btn btn-secondary" name="file" value="Select files" id="file"/>
        <input id="file" name="file" type="submit" value="Upload" class="btn btn-primary"/>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StampBidding/Views/Bidding/Delete.cshtml
@model StampBidding.Models.Bidding

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bidding</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Uuid)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

StampBidding/Views/Bidding/Details.cshtml
@model StampBidding.Models.Bidding

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Bidding</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Uuid)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

StampBidding/Views/Bidding/Edit.cshtml
@model StampBidding.Models.Bidding

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Bidding</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ItemId" class="control-label"></label>
                <select asp-for="ItemId" class="form-control" asp-items="ViewBag.ItemId"></select>
                <span asp-validation-for="ItemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

StampBidding/Views/Bidding/Index.cshtml
@model IEnumerable<StampBidding.Models.Bidding>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Uuid)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>